### ISSUE TITLE
Detecting if valorant is open

### ISSUE THREAD

**Issue by maipley** [HeyM1ke/Assist#107]
How did you make the program to recognize if valorant is open or not??

**Comment by 5H4D0WILA** [comment]
i would assume by checking for the lockfile
From what i understand the lockfile only exists when valorant is open, so checking if that file exists should tell you if the game is open or not

**Comment by KillaBoi** [comment]
It actually doesn't check for the lockfile but the executable running itself. It's located in the AssistBackgroundClient and the relevant lines are [HERE](https://github.com/AssistTeam/AssistBackgroundClient/blob/72f0f3b74cce3a7c728162aba864219c23cbba6c/AssistBackgroundClient/Services/ValorantGameController.cs#L25-L43)
