### ISSUE TITLE
Sarmad collection incorrect price VP

### ISSUE THREAD

**Issue by NugithChan** [HeyM1ke/Assist#119]
![image](https://user-images.githubusercontent.com/65823389/182096001-efd59da8-4af1-4b29-bc84-829889d813e9.png)

Sarmad phantom costs 99,999VP. Sorry if the crop is weird.

**Comment by Sindavar** [comment]
![image](https://user-images.githubusercontent.com/40722515/207200162-d6a55b28-8907-48a9-b6f3-c6c59da03355.png)
