### ISSUE TITLE
I got permanently banned for asssit

### ISSUE THREAD

**Issue by Celionlol** [HeyM1ke/Assist#126]
As the title reads, I actually got banned just for using assist. I have no other apps for valorant exept assist and blitz and I got permanently banned for 3rd party applications. Of course I wrote a ticket to riot games support to unban me, but they just told me that they wont unban me and I also got a HWID ban for 4 months. RIP 300€ account
So what should I do????

**Comment by nnbaocuong99** [comment]
omg .. im just uninstalled assist for 2 weeks ago. im so sorry for hearing this bro. i hope there still a way to solve this

**Comment by HeyM1ke** [comment]
Assist is not bannable. So I hate to tell you that this is not the cause.
