### ISSUE TITLE
Ion Ares is 99,999 RP

### ISSUE THREAD

**Issue by KayblDerpy** [HeyM1ke/Assist#130]
I'm just checking my shop and the Ion Ares is just 99,999 RP for no particular reason. I've tried reloading the application but no difference.
![image](https://user-images.githubusercontent.com/86759715/203906506-f19f744a-21ff-4fa4-93da-3abdb97f39eb.png)

**Comment by Lucky-56** [comment]
same with crimsonbeast judge and soulstrife guardian
![image](https://user-images.githubusercontent.com/55949451/206133384-89fd9056-0ade-46e3-b1d1-eb3ff1e3f605.png)

**Comment by nanikahana** [comment]
same with chronovoid and sarmad phantom
![image](https://user-images.githubusercontent.com/114847794/206945917-3bf38490-6c58-4d82-a37c-834c20bc5bb4.png)
![image](https://user-images.githubusercontent.com/114847794/206945976-8ee4232b-382c-43ae-9db4-15ef6930a3c6.png)

**Comment by Luis2000yt** [comment]
![image](https://user-images.githubusercontent.com/106380105/207146123-2deef79c-517e-41f2-bb43-ae64379922ca.png)
Crimsonbeast Sheriff has the same problem

**Comment by KayblDerpy** [comment]
![why](https://user-images.githubusercontent.com/86759715/208220780-ee797884-6e42-4ae8-a160-f95374ee1017.png)
Apparently the Kohaku & Matsuba collection and the Caeruleus knife (could be the collection) are also broken.
