### ISSUE TITLE
Assist App Beta closes when accessing Night Market

### ISSUE THREAD

**Issue by junmar0117** [HeyM1ke/Assist#147]
Title
![image](https://user-images.githubusercontent.com/77731690/210969982-9934638e-2a0d-4c49-8165-2a3f3e53b7ba.png)

**Comment by KayblDerpy** [comment]
Probably because Night Market ended, and Assist is trying to fetch Night Market items but the Riot API doesn't have the items/doesn't want Assist accessing it and Assist throws an error or something.
