### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sezzyaep** [HeyM1ke/Assist#149]
Hello when i try build source i got this error how can i fix it?

NETSDK1045 The current .NET SDK does not support targeting .NET version 7.0. Target .NET 5.0 or lower, or use a .NET SDK that supports .NET 7.0.

i m installed NET 7.0.1 and i got same error

**Comment by overestimate** [comment]
Stale issue, but for anyone else that experiences this please run `dotnet --version` and make sure it matches the required version.
