### ISSUE TITLE
Setup Error "Source and destination path must have identical roots. Move will not work across volumes."

### ISSUE THREAD

**Issue by yuhkix** [HeyM1ke/Assist#153]
So apparently I'm getting a setup error when trying to install Assist which has been going on for some days now even after checking if i have everything needed installed.
The Error says the following: 
![image](https://user-images.githubusercontent.com/74727805/212761507-3ef57543-520a-4918-b5fc-f7722c14d535.png)

Please let me know if there's anything I can do on my side or if I should just wait for the next update.

**Comment by HeyM1ke** [comment]
I'm working on a Portable version of assist. Which will allow you to just have Assist live in a folder, it wont be done for awhile though. I really want to get this working as this error is out of my hands.

**Comment by yuhkix** [comment]
> I'm working on a Portable version of assist. Which will allow you to just have Assist live in a folder

I appreciate your answer a lot and thanks for the hard work you're putting into this project.
I'm really looking forward to this!

**Comment by vitivalkoinen** [comment]
I have experienced the same problem, but there is one way that users might be able to work around this issue.

If you have changed the temporary file storage directory to something other than the C drive, you can work around this problem by temporarily moving it back to the C drive.

Specifically, change the environment variables "TMP" and "TEMP" to "C:\Temp".

This is not a radical solution, but if you want to install anyway, please try it.

**Comment by ngocanthony** [comment]
> I have experienced the same problem, but there is one way that users might be able to work around this issue.
> 
> If you have changed the temporary file storage directory to something other than the C drive, you can work around this problem by temporarily moving it back to the C drive.
> 
> Specifically, change the environment variables "TMP" and "TEMP" to "C:\Temp".
> 
> This is not a radical solution, but if you want to install anyway, please try it.

Thank you for sharing for solution, it worked for me
