### ISSUE TITLE
Price(s) in store not updated? 

### ISSUE THREAD

**Issue by marchingon12** [HeyM1ke/Assist#156]
The price on the melee is wrong. I'm guessing either the database the API is being used for hasnt been updated or smth else is causing the price to display wrongly.

![Assist_fL0ba2J5HQ](https://user-images.githubusercontent.com/41235480/215257542-c020f05f-aaf0-4c79-bd53-894627fcd65e.png)

**Comment by HeyM1ke** [comment]
Will be fixed later today :D
