### ISSUE TITLE
Game Mode stuck on "Check Your Browser"

### ISSUE THREAD

**Issue by Ab00v** [HeyM1ke/Assist#163]
After I connect the application to my discord account it says "Check Your Client" and when I go to my client, it says "Check Your Browser". 

In the browser:
![image](https://user-images.githubusercontent.com/122667291/219875130-436e1697-91cd-4e70-9287-1f4c8f45fecc.png)

In the client:
![image](https://user-images.githubusercontent.com/122667291/219875161-841bea10-7a2b-4a95-bf1c-7edf5bacc781.png)

**Comment by HeyM1ke** [comment]
Fixed
