### ISSUE TITLE
Store page cannot get the current bundle(s)

### ISSUE THREAD

**Issue by airplaneboy14mc** [HeyM1ke/Assist#164]
I've had this issue with assist on the store page not being able to get the current bundle, the app is up to date, it is able to pull my store items but not the bundles (2 bundles available right now).

**Will update with a screenshot later, cannot get a screenshot at the moment**

Specs (If helpful):
I am running on Windows 11 Home
Intel 10th gen i5 CPU
NVIDIA RTX 3050
16GB DDR4 RAM

**Comment by Kxsumi** [comment]
It doesnt update bundles automatically I don't believe. You need to wait for Mike to update them manually. So as of now, they won't show.
