### ISSUE TITLE
Valorant wont run while using VPN

### ISSUE THREAD

**Issue by Cazzy7819** [HeyM1ke/Assist#170]
I used a VPN and split tunneling to avoid increasing my ping on Valorant, I made sure every Assist and Valorant program were to not be used by the VPN yet I never manged to get it to work.
After uninstalling Assist everything worked perfectly fine.

**Comment by Kxsumi** [comment]
This is not an Assist issue, Riot's login system prevents the use of VPNs. Also, ping increase doesn't matter until you go above ~120. Which VPN do you use, could also be the cause.

**Comment by Cazzy7819** [comment]
Figured, issue came back after a while. Don't know why uninstalling Assist originally fixed it. I use ExpressVPN.
