### ISSUE TITLE
Store tab issues

### ISSUE THREAD

**Issue by nnbaocuong99** [HeyM1ke/Assist#172]
Sometime the current bundle(s) are ***not showing*** or ***keep stuck*** on `Loading...` (my internet always fine and also my pc performance

![image](https://user-images.githubusercontent.com/100349044/229964207-a0d19ad5-fac6-4b62-a3ec-c082e7313b08.png)

**Comment by Kxsumi** [comment]
Some bundles do not have images as they don't exist in the Assist DB yet. Not sure if Altitude does, but I know it hasn't been added as of yesterday. May be different now.

**Comment by HeyM1ke** [comment]
Yup this is my bad, i hope to fix it soon. It has happened with some images as well. When i update the images, sometimes i get a connection timeout due to my home's wifi. It makes images corrupted on the server. I plan to refresh everything within the next 1-2 days.

**Comment by nnbaocuong99** [comment]
tbh this is a really good tools and i must admit that <3 keep up the good work guys i will keep reporting if i saw any single error or bug to help u guys to make it better

**Comment by floxay** [comment]
> When i update the images, sometimes i get a connection timeout due to my home's wifi. It makes images corrupted on the server.

Just run the update service on server side?

**Comment by nnbaocuong99** [comment]
> > When i update the images, sometimes i get a connection timeout due to my home's wifi. It makes images corrupted on the server.
> 
> Just run the update service on server side?

wtf do u mean bro? the application always update automatically itself when we open it?

**Comment by floxay** [comment]
That was a reply to Mike's comment, has nothing to do with the Assist client/app you use.
