### ISSUE TITLE
Can't log in with both methods

### ISSUE THREAD

**Issue by Eurothopia** [HeyM1ke/Assist#173]
When I try to log in with username, it shows this error
![image](https://user-images.githubusercontent.com/90931142/232036549-f562f2e8-c6d3-4f00-aa10-1311d880e74f.png)

And with the client way nothing happens
Probably API change or smthin

**Comment by junmar0117** [comment]
same
![image](https://user-images.githubusercontent.com/77731690/232107349-2d710b39-3718-4499-906d-3290903d23c4.png)

**Comment by HeyM1ke** [comment]
Fixed
