### ISSUE TITLE
Password expired

### ISSUE THREAD

**Issue by H4K0N42** [HeyM1ke/Assist#178]
Can you store the password of an account obfuscated in a file? Almost everytime I want to change the acc I have to login again, probably beacuse the session expired. Maybe you could add this with a toggle in the settings.

**Comment by NotReddHoodie** [comment]
I think a local password save wouldn't be very secure, though, it should be looked into if there is a way to stop session expires.

My guess is when you switch accounts, the local riot session logs you out of all accounts and into another, therefore forcing you to log in again on the other accounts locally, though I could be wrong
