### ISSUE TITLE
Temporary disconnect while using Assist

### ISSUE THREAD

**Issue by Ramen5914** [HeyM1ke/Assist#180]
This only happens when I have launched Valorant through Assist launcher.

Basically, after a while of playing Valorant (10 - 15 minutes), the friends list will say offline, and assist launcher will close. There is no change in gameplay like lag or anything else noticeable. When the game finished it will make me restart Valorant saying that I am offline. It gives me error code VAL 1.

**Comment by OzymoGit** [comment]
is laucher this discontinued guys? I like this alot

**Comment by Ramen5914** [comment]
Its not discontinued
