### ISSUE TITLE
Login codes

### ISSUE THREAD

**Issue by tabaca666** [HeyM1ke/Assist#185]
For about 3-4 weeks I don't receive login codes to my email address. Everything worked before and I didn't change anything on my acc etc. If I am logging in at riot website and client - it's all working. Accounts without two-step verification still works without any problems.
Any fix for this?

![sadasetetwertwe](https://github.com/HeyM1ke/Assist/assets/160143764/93ffffdf-fcdb-419d-8557-4cf4cd6c961d)

**Comment by u200bpl** [comment]
Login via the Riot Client and then use the code you received in Assist.
