### ISSUE TITLE
Store not showing any skins or prices

### ISSUE THREAD

**Issue by AdvayG** [HeyM1ke/Assist#190]
![image_2024-03-08_093359451](https://github.com/HeyM1ke/Assist/assets/159689561/d23c0dac-8806-43f4-a013-1dea7018b0aa)
Store page in Assist doesn't show any skins just shows error and can't find the bundle on the server

**Comment by oaus** [comment]
You need update to the lastest version, you can download from https://github.com/HeyM1ke/Assist/releases/tag/release-1.0.0
