### ISSUE TITLE
Rich presence doesn't update the agent in the range

### ISSUE THREAD

**Issue by taedium8vitae** [HeyM1ke/Assist#192]
This isn't a huge bug but when you go in the range, the default agent is Sova and even if you change agent down the line, Assist is still going to show Sova as the agent in Discord Rich Presence. Re-enabling Rich Presence module does nothing.
You could maybe add a specific check for the range (and custom games) every few seconds to verify that the agent hasn't changed (that is if valorant doesn't produce a specific event that could be detected when changing agent).

**Comment by HeyM1ke** [comment]
Hey! As much as I would love to make this work. At the moment, it seems the data being sent is always going to be Sova. Seems to be a VAL limitation.
