### ISSUE TITLE
Application too big for 720p monitor

### ISSUE THREAD

**Issue by SouperNinja** [HeyM1ke/Assist#2]
I have a tiny 720p monitor, and when using the app there's no way to fullscreen or resize it in any way so a little bit of the bottom is cut off. The app is still perfectly usable, just a minor thing.

**Comment by SouperNinja** [comment]
![image](https://user-images.githubusercontent.com/67909791/152663559-0b8d5955-bca9-4103-bd88-701b52932a9e.png)
idk if that helps but that's what it looks like

**Comment by gxjakkap** [comment]
Faced similar problem when Assist decided to launch in my second monitor which was 1366x768 and not being able to resize it nor move it to my main monitor.

**Comment by Tresillo2017** [comment]
> Faced similar problem when Assist decided to launch in my second monitor which was 1366x768 and not being able to resize it nor move it to my main monitor.

Using the windows key and right or left arrows you can move the window without using the mouse.

Hopes that help.

**Comment by RumbleMike** [comment]
Assist is not a full screen launcher, that would just be weird. The New UI that is releasing will be at a resolution of 1024x601 and will scale up from there.

**Comment by gxjakkap** [comment]
> > Faced similar problem when Assist decided to launch in my second monitor which was 1366x768 and not being able to resize it nor move it to my main monitor.
> 
> Using the windows key and right or left arrows you can move the window without using the mouse.
> 
> Hopes that help.

I can move other programs just fine, except for Assist. Guess it has to do with Assist lacking maximize functionality.

But that's my new knowledge for today though. Thanks a bunch!

**Comment by HeyM1ke** [comment]
The new Launch Version has two Resolutions you can use, Id Recommend taking a look.
