### ISSUE TITLE
Hack Knife Pricing Wrong on Store Tab

### ISSUE THREAD

**Issue by Sentientnapkin** [HeyM1ke/Assist#20]
![Assist Hack Bug](https://user-images.githubusercontent.com/73544597/156273004-aeb05d45-c8f1-4152-836c-e6d3270fcb46.png)

Hack knife shows up as 99,999 vp on store tab.

**Comment by Sentientnapkin** [comment]
I reopened Assist and it still shows 99,999

**Comment by HeyM1ke** [comment]
Fixed
