### ISSUE TITLE
An option to turn off Rich Presence on the assist launcher

### ISSUE THREAD

**Issue by Expzr** [HeyM1ke/Assist#24]
As the title says, an option to be able to turn off Rich Presence for the assist launcher because I just don't like to have an RPC on while playing valorant.

Can't mark it as a **Request Feature**

**Comment by HeyM1ke** [comment]
This was a feature in the inital version of assist, but was causing issues. This will be apart of a future version.

**Comment by HeyM1ke** [comment]
Added in the Official Launch Version
