### ISSUE TITLE
Copy over settings from one account to another

### ISSUE THREAD

**Issue by Ardstand** [HeyM1ke/Assist#26]
There is a way to copy over all settings from one account to another including crosshairs, agent profiles etc.

Its a useful feature for alts and since they already login to assist, it could be easier to copy settings between accounts.

I would love to help you out with this, so feel free to contact me @ [Ardstand](https://github.com/Ardstand)

Thank you for reading this suggestion!

**Comment by HeyM1ke** [comment]
Yep! Coming in a future version!

**Comment by DevOFVictory** [comment]
Great idea! :)
