### ISSUE TITLE
Deceive integration

### ISSUE THREAD

**Issue by skay1994** [HeyM1ke/Assist#3]
Integration with **Deceive** to stay offline in game chat, or allow to choise a **.exe** to launcher on click in *play button*

https://github.com/molenzwiebel/Deceive

Your repository don't have labels, i'm try used to mark as **"Request Feature"**

**Comment by JonJaded** [comment]
I was trying to find out if there's a way to use launch commands to force it to load deceive but I can't seem to edit the option.
