### ISSUE TITLE
[FEATURE REQUEST] Import/export accounts

### ISSUE THREAD

**Issue by anirudhgupta109** [HeyM1ke/Assist#31]
Ability to export signed in accounts (I'm unsure of riot auth being exported but username/password should be possible) to a file and then import them on a fresh Assist install

Background: I tend to reset my windows setup periodically and signing into each of the accounts I use can become extremely annoying (primary reason for me using username/pass instead of riot auth cause it used to sign me out every 5 days or so)

**Comment by HeyM1ke** [comment]
100% a security problem
