### ISSUE TITLE
Assist does not launch the game if it's in another disk

### ISSUE THREAD

**Issue by SKYREXoff** [HeyM1ke/Assist#34]
Hello!
I had a problem that Assist could not launch the game and just close after saying "Lauching the game" or something.
I found that my game was installed on my "E:\" disk, and the Assist on my "C:\" (which are 2 differents disk and not just paritions).
So to solve the problem I had to uninstal the Assist and reinstall it on the other disk.

**Comment by HeyM1ke** [comment]
Should be fixed
