### ISSUE TITLE
[Suggestions] alt accounts + qol stuff

### ISSUE THREAD

**Issue by simplictyy** [HeyM1ke/Assist#49]
more alt accounts to change to

see if current account is online/ingame

instead of opening assist and being logged in to the default account
instead, let it choose from the start

whenever u login to an account it uses a fixed settings and controls instead of using last controls so for example:
my fixed settings in assist will be 0.471 and controls are q,e,v,x
i exit valorant with 1 Sensitivity and ability controls are z,q,c,x
when i open valorant again my settings will change back to 0.471 and q,e,v,x

**Comment by MayowaAk** [comment]
Valorant doesn't save the user key binds to the pc only a local backup and video and audio settings,
![Screenshot 2022-05-22 201045](https://user-images.githubusercontent.com/70532397/169711877-33f48f7f-d805-45bf-9938-c169dfeee781.png)
![gameuse](https://user-images.githubusercontent.com/70532397/169711878-9a1e8ccc-7da2-43a1-b39a-63dc59fe1bed.png)
