### ISSUE TITLE
[Feature Request] Add Deceive as a toggle to launch the game with Invisible status?

### ISSUE THREAD

**Issue by naheedroomy** [HeyM1ke/Assist#52]
Would like a feature that integrates [Deceive ](https://github.com/molenzwiebel/Deceive/releases/tag/v1.11.0)(the program used by many people to launch the game in invisible status so that nobody can see if you're online).
 
 Would be a really cool feature

Other than that, all good. Love the work, Mike!

**Comment by HeyM1ke** [comment]
This will be coming in the future!

**Comment by naheedroomy** [comment]
> This will be coming in the future!

Cool, thanks!!
