### ISSUE TITLE
[FEATURE REQUEST] Uninstaller

### ISSUE THREAD

**Issue by Pi3Gey** [HeyM1ke/Assist#53]
Please include a uninstaller via control panel or through exe file. 
There's no way to remove the registry files along with the software if one doesn't need it anymore.

**Comment by riahc3** [comment]
You gotta be shitting me....

I installed it to try it out and it doesnt have a proper uninstaller?

What is this, 1996?

**Comment by HeyM1ke** [comment]
Released with the newest version of the installer.

**Comment by Pi3Gey** [comment]
Thankyou for the quick update, I appreciate your efforts
