### ISSUE TITLE
JSON error on login

### ISSUE THREAD

**Issue by rumble19** [HeyM1ke/Assist#56]
Hello, I am currently unable to login to assist either by logging in directly or through the riot login option in the program. I do have 2 factor enabled on my account if that makes a difference. Attached is the log from one of my attempts.

I am on a fully up to date windows 11 PC. 

The exact error message is:
`The JSON value could not be converted to System.Int64. Path: $.pw.cng_at | LineNumber: 0 | BytePositionInLine: 146.`

[Assist_Log_9.txt](https://github.com/HeyM1ke/Assist/files/8672582/Assist_Log_9.txt)

Let me know if I can provide any more useful info.

**Comment by HeyM1ke** [comment]
With what login method are you trying to authenticate with? Username/Password or Social Authentication?

**Comment by rumble19** [comment]
User and password. I have not tried the social login. I have tried both the in-app login (the left button) and the Riot login (the right button) with the same error on each.

**Comment by HeyM1ke** [comment]
Hmm, Very interesting. Ill take a look soon.

**Comment by HeyM1ke** [comment]
Should be fine now.
