### ISSUE TITLE
Play button does not launch the game.

### ISSUE THREAD

**Issue by Mrgoldy-YT** [HeyM1ke/Assist#57]
It might be because I installed the game in a different path, not in the default path. So, perhaps add a feature to the installer to select the directory where the game is installed…?

**Comment by HeyM1ke** [comment]
Launching the game is handled by the riot client. 

Check your install folder, and check if there is a modules folder.

**Comment by Mrgoldy-YT** [comment]
NEVERMIND! After the new update, everything works!
