### ISSUE TITLE
Pollutes my desktop with an empty json file every time i delete it

### ISSUE THREAD

**Issue by pintermor9** [HeyM1ke/Assist#69]

**Comment by pintermor9** [comment]
and i mean totally empty so no "{}" just ""

**Comment by pintermor9** [comment]
i think something like AssistInstallSettings.json and i think it happens when i update Assist but im not sure

**Comment by LOCKhart07** [comment]
I've uninstalled Assist, but that file gets created on my desktop after every reboot
