### ISSUE TITLE
Can't use google login

### ISSUE THREAD

**Issue by winnipeg21** [HeyM1ke/Assist#7]
Trying to signin through riot using my google account as I always do and I get this error 

![image](https://i.pingu.ga/trazf.png)

**Comment by pe3ep** [comment]
1. Go to riot account managment (https://account.riotgames.com/)
1. login
1. press this button on the left
![image](https://user-images.githubusercontent.com/74493360/152729036-d45be162-f7ab-4ed6-8c7a-c5401e2e7bab.png)
1. set up your riot login
![image](https://user-images.githubusercontent.com/74493360/152729212-06ba7981-11b7-410e-a458-e06de7d89259.png)
1. login with your new riot info

Currently, its not possible to login with google, but I found this solution

**Comment by winnipeg21** [comment]
Alright, that worked. Should be possible to sign if you open the site in chrome or something. Maybe even using the same method Epic Games does where it'll send you to chrome then send that data back.

**Comment by pe3ep** [comment]
agreed

**Comment by baaannnaaannn** [comment]
same problem
