### ISSUE TITLE
[Suggestions] qol stuff | launch for other riot games

### ISSUE THREAD

**Issue by degu-Tanya** [HeyM1ke/Assist#70]
Since I play as much league as I do valorant it would be nice to have a simple launch options for league of legends client.
I love this launcher for valorant since its the only one I found that also shows ingame shop. But having the option to launch league of legends with it would be a nice QOL.

I got multiple league smurfs that also is used on valorant so this would be a nice qol change

here is a quick mockup.
could also add it as a setting in the client and it wont show the icon before you enable it
![leauge and runetera](https://user-images.githubusercontent.com/100243423/169487306-698de86e-1a8c-402f-8a0b-b103430da6c9.png)

When you are on league
![leauge and runetera on league](https://user-images.githubusercontent.com/100243423/169497677-6d306469-45d0-4303-8aa0-a5d4116ccbd6.png)
Reason for 2nd name under name#number is because riot allows own league name that is attached to riot#id and that specific region
2nd icon is just their game Runetera (I dont play it but I just added it)

And if the app is really loved having match history under name/where its blank could be added also.

**Comment by riahc3** [comment]
Im pretty sure you LoL people have a lot of apps that already do this. You have had the game since 2009.

Im just against mixing Valorant and LoL stuff.

**Comment by degu-Tanya** [comment]
Yes there is, I'm currently using TcNo Acc Switcher but it does not have a cool shop display like this one
