### ISSUE TITLE
[FEATURE REQUEST] Ability to reorder accounts in accounts tab

### ISSUE THREAD

**Issue by deducted** [HeyM1ke/Assist#87]
The title basically says it all. Make it so that users are able to reorder accounts into a specific order from left to right. I know I would like it if I could always have my main account far left, but currently I'd have to log out of all accounts and relog with that account first to have it on the far left.

**Comment by John-Kryspin** [comment]
@HeyM1ke Let me try taking this one.

**Comment by HeyM1ke** [comment]
For Sure, but hold out for a bit. I have some changes coming to profiles in general. So the page is going to be swapped around.
