### ISSUE TITLE
Made too many request now Riot has blocked my IP.

### ISSUE THREAD

**Issue by xjkbro** [HeyM1ke/Assist#90]
I recently updated to the newest version of Assist and tried to launch Valorant on my main account. Once I did this I went to the bathroom to take a quick piss and I come back with the game still trying to load. So I closed down the application and relaunched it and this time it tells me that it can't connect to all my accounts and I should resign in to them. When I do that, the Riot login tells me "We've received your request. Please wait a few minutes and try again." when I try to login on all my accounts. When I sign into the main launcher, it tells me that I provided the wrong credentials. It seems like Riot has blocked my IP due to the Assist launcher having problems when I was trying to play the game. I'm thinking that the block will only be up for 24 hours. I am going to try and l submit a ticket to expedite the process.

Edit: It seems like Riot had just blocked me for an hour.

**Comment by HeyM1ke** [comment]
This was an issue with some Riot Users today and not just people using Assist.
