### ISSUE TITLE
Not Able to Login 

### ISSUE THREAD

**Issue by papadon6969** [HeyM1ke/Assist#96]
Using Assist from the starting but facing these issue recently 
1. Accounts login get logged out after a day or by system restart 
2. After the latest update I am not able to loggin 

![1](https://user-images.githubusercontent.com/80568648/171558981-0bc68625-e047-4857-820b-c619084f4585.jpg)
![2](https://user-images.githubusercontent.com/80568648/171559201-bb1cbca3-c980-4d26-8ab8-443f53fe5d9a.jpg)

**Comment by mustachebutter** [comment]
Maybe try resetting your machine one more time? Or check your credentials (I know this is unlikely but trying would not take a lot of effort). I was able to add my alt account with the latest patch (v1.0.0.8)

**Comment by caterpillowo** [comment]
I have the same issue. All of my accounts on assist got logged out and I was unable to log in regularly through riot client or on my phone while connected to my wifi. However, my phone is able to login through the website while on mobile data, and so was my friend who lives in another household. It appears something has caused Riot to not allow logins from devices connected to my wifi.
